workflowVersion: 1.0.0
sources:
    openapi:
        inputs:
            - location: ./apps/web/openapi.json
        overlays:
            - location: https://raw.githubusercontent.com/dubinc/dub-node/main/codeSamples.yaml
        output: ./apps/web/openapi.json
targets: {}
